"""
_transpile_qrisk3.py  —  build-time tool (run once, not used at runtime)

Mechanically converts the official ClinRisk QRISK3-2017 C source
(_qrisk3_clinrisk_source.c) into a faithful Python module (qrisk3_engine.py).

We transpile rather than hand-retype because the QRISK3 coefficient set is huge
and the prompt's #1 fidelity rule is: don't hand-transcribe a big table and trust
it. A line-by-line mechanical conversion plus the 48-profile verification test
(tests/test_scoring.py) is the safe path.

C -> Python is straightforward here because the C functions are pure arithmetic:
  * `pow(a, b)`            -> `pow(a, b)`            (Python builtin, identical)
  * `log()` / `exp()`     -> `math.log()` / `math.exp()`
  * `(smoke_cat==1)`       -> stays as-is; Python `True * x == x`, `False * x == 0`
  * `double`/`int` decls   -> dropped; trailing `;` dropped
  * array literals         -> Python lists
Run:  python3 _transpile_qrisk3.py
"""
import re
import pathlib

HERE = pathlib.Path(__file__).parent
SRC = (HERE / "_qrisk3_clinrisk_source.c").read_text()


def grab_function(c_text, label):
    """Return the C body of the function that follows a `Female`/`Male` line."""
    # Each function is introduced by a bare line 'Female' or 'Male', then a
    # C comment block, then `static double cvd_*_raw(...) { ... return score; }`.
    start = c_text.index(label)
    sig_start = c_text.index("static double", start)
    brace = c_text.index("{", sig_start)
    # find matching close brace
    depth = 0
    i = brace
    while i < len(c_text):
        if c_text[i] == "{":
            depth += 1
        elif c_text[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    signature = c_text[sig_start:brace]
    body = c_text[brace + 1:i]
    return signature, body


def parse_params(signature):
    inside = signature[signature.index("(") + 1: signature.rindex(")")]
    params = []
    for tok in inside.split(","):
        tok = tok.strip()
        if not tok:
            continue
        # tok like "int age" or "double bmi"
        name = tok.split()[-1]
        params.append(name)
    return params


def transpile_body(body):
    out_lines = []
    # First, collapse array declarations that span multiple lines into one line.
    # Replace C comments /* ... */ with python comments.
    # We'll process line by line, but arrays span lines, so join then re-split smartly.
    text = body

    # Convert block comments to nothing (we add our own).
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)

    # Handle array declarations: double NAME[n] = { ... };  (may span lines)
    def array_repl(m):
        name = m.group(1)
        values = m.group(2)
        nums = [v.strip() for v in values.split(",") if v.strip() != ""]
        # keep a trailing ';' so the later split(';') treats this as one statement
        return f"{name} = [{', '.join(nums)}];"
    text = re.sub(r"double\s+(\w+)\s*\[\s*\d+\s*\]\s*=\s*\{(.*?)\}\s*;",
                  array_repl, text, flags=re.DOTALL)

    for raw in text.split(";"):
        line = raw.strip()
        if not line:
            continue
        if line.startswith("["):  # leftover bracket fragments – skip empties
            continue
        # drop type keywords used in declarations
        line = re.sub(r"^\s*double\s+", "", line)
        line = re.sub(r"^\s*int\s+", "", line)
        # math functions
        line = re.sub(r"\blog\s*\(", "math.log(", line)
        line = re.sub(r"\bexp\s*\(", "math.exp(", line)
        # `pow(` is a Python builtin already – leave it.
        # `return score` handling
        line = line.replace("return score", "return score")
        # collapse internal newlines/whitespace
        line = re.sub(r"\s+", " ", line).strip()
        out_lines.append(line)
    return out_lines


def emit(name, params, body_lines):
    py = []
    py.append(f"def {name}({', '.join(params)}):")
    for l in body_lines:
        py.append(f"    {l}")
    return "\n".join(py)


def main():
    fsig, fbody = grab_function(SRC, "Female")
    msig, mbody = grab_function(SRC, "Male")
    fparams = parse_params(fsig)
    mparams = parse_params(msig)

    fpy = emit("cvd_female_raw", fparams, transpile_body(fbody))
    mpy = emit("cvd_male_raw", mparams, transpile_body(mbody))

    header = '''"""
qrisk3_engine.py  —  AUTO-GENERATED. DO NOT EDIT BY HAND.

Generated by _transpile_qrisk3.py from the official ClinRisk QRISK3-2017 C source.
Original algorithm (c) 2017 ClinRisk Ltd, released under the LGPL (see
QRISK3_CLINRISK_LICENSE.txt). The two functions below are a faithful mechanical
translation of cvd_female_raw / cvd_male_raw and return a 10-year CVD risk as a
PERCENTAGE (0-100).

ClinRisk's licence requires that anyone relying on this code verify it reproduces
the results at https://qrisk.org. We do that automatically in
tests/test_scoring.py against 48 reference profiles shipped with the validated
`QRISK3` R package (Li, Sperrin & van Staa).
"""
import math


'''
    output = header + fpy + "\n\n\n" + mpy + "\n"
    (HERE / "qrisk3_engine.py").write_text(output)
    print("Wrote qrisk3_engine.py")
    print(f"  female params: {fparams}")
    print(f"  male params:   {mparams}")


if __name__ == "__main__":
    main()
